# image Python
FROM python:3.9

# répertoire de travail
WORKDIR /app


COPY requirements.txt requirements.txt
COPY get_around_pricing_ML.csv /app
COPY get_around_delay_analysis.csv /app

# dépendances
RUN pip install -r requirements.txt


COPY . .

# port Streamlit
EXPOSE $PORT

# Lance Streamlit
CMD streamlit run app.py --server.port=$PORT --server.enableCORS=false
