# Utiliser une image officielle de Python
FROM python:3.9

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier requirements & dataset
COPY requirements.txt requirements.txt
COPY get_around_pricing_ML.csv /app
COPY get_around_delay_analysis.csv /app

# Installer les dépendances
RUN pip install -r requirements.txt

# Copier le reste du code
COPY . .

# Exposer le port utilisé par Streamlit
EXPOSE $PORT

# Lancer Streamlit
CMD streamlit run app.py --server.port=$PORT --server.enableCORS=false
